### ISSUE TITLE
Can't find opentok.js

### ISSUE THREAD

**Issue by PrimeObjects** [aoberoi/cordova-plugin-opentokjs#14]
I got the following error
Failed to load resource: net::ERR_FILE_NOT_FOUND file:///android_asset/www/js/opentok.js
Question : is opentok.js automatically generated when doing the build? Or where should I get it?  

ReferenceError: OT is not defined
    at Scope.$scope.loadWebRTC (file:///android_asset/www/app/default/default.js:82:9)
    at Scope.$scope.initialForm (file:///android_asset/www/app/default/default.js:30:20)
    at new <anonymous> (file:///android_asset/www/app/default/default.js:90:12)
    at invoke (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:13012:17)
    at Object.instantiate (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:13020:27)
    at file:///android_asset/www/lib/ionic/js/ionic.bundle.js:17289:28
    at self.appendViewElement (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:48435:24)
    at Object.switcher.render (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:46629:41)
    at Object.switcher.init (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:46549:20)
    at self.render (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:48295:14) <ion-nav-view name="menuContent" class="view-container" nav-view-transition="android">

**Comment by andreportaro** [comment]
Up. My Ionic app doesn't find it either.
